# Generated by Django 5.1.2 on 2024-12-15 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=models.CharField(choices=[('others', 'others'), ('male', 'male'), ('female', 'female')], default='others', max_length=255),
        ),
    ]
